<?php

/**
 * Created by PhpStorm.
 * User: just
 * Date: 05.02.16
 * Time: 14:16
 */
class Square extends Rectangle
{
    public function __construct($size, $image)
    {
        parent::__construct($size, $size, $image);
    }

    public function resize($width, $height = null)
    {
        parent::resize($width, $width); // TODO: Change the autogenerated stub
    }

    public function getArea()
    {
        return $this->width * $this->width;// TODO: Implement getArea() method.
    }

}